name: Minimal Test

on:
  push:
    branches: [ master ]

jobs:
  basic-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Basic test
      run: |
        python --version
        echo "Workflow is working!"
        ls -la