name: Cross-Platform Testing

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy scipy
      
    - name: Install package
      run: |
        cd cohens_d_package
        pip install -e .
        
    - name: Run standard tests
      run: |
        cd cohens_d_package
        python -m pytest tests/ -v --tb=short
        
    - name: Run validation tests
      run: |
        cd cohens_d_package
        python -c "import sys; sys.path.append('.'); from cohens_d import cohens_d; import numpy as np; print('Testing basic functionality...'); result1 = cohens_d([1, 2, 3], [4, 5, 6]); print(f'Basic test: {result1:.3f}'); result2 = cohens_d([1, 2, 3]); print(f'One-sample test: {result2:.3f}'); print('All basic tests passed!')"
        
    - name: Test package installation
      run: |
        cd cohens_d_package
        python -c "import cohens_d; print('Cohen d import successful')"
        python -c "from cohens_d import cohens_d; print('Function import successful')"
        python -c "from cohens_d import cohens_d; import numpy as np; print(f'Basic test: {cohens_d([1,2,3]):.3f}')"